ptz_horizontal_convert=0
ptz_vertical_convert=0
infraredlamp_level=1
whitelamp_level=1
ircut_convert=0
speaker_level=0
hardware_change_lamp_mode=1
photoresistor_type=0
photoresistor_level=0
max_ptz_horizontal_step=3150
max_ptz_vertical_step=1200
ptz_horizontal_speed=2000000
ptz_vertical_speed=3000000
ptz_move_volume=80
af_protocol=0
custom_io_func1=0
custom_io_func2=0
double_lamp_support=1
ptz_support=0
gb28181_support=1
cloud_support=1
onvif_set_image_support=1
