config_version=1
manufacture=Vatilon
location=ShenZhen
devtype=H43
version=V1.14.48-20240903
devno=PPXCAO0AA55FD6CC15
serial_num=989FEA22D1F1F9AF
nickname=H43
channelname=Channel0
language=1
timezone=27
voice=2
auto_reboot_enable=0
auto_reboot_wday=0
auto_reboot_time=0:0:0
ntp_enable=1
ntp_server=time.windows.com
ntp_port=123
ntp_interval2=43200
dst_enable=0
dst_mode=0
dst_start_month=3
dst_start_week=2
dst_start_day=0
dst_start_time_hour=2
dst_start_time_minute=0
dst_start_time_second=0
dst_end_month=11
dst_end_week=1
dst_end_day=0
dst_end_time_hour=2
dst_end_time_minute=0
dst_end_time_second=0
dst_offset_time=60
venc_type0=0
venc_width0=1920
venc_height0=1080
venc_framerate0=25
venc_gop0=4
venc_rcmode0=1
venc_bitrate0=810
venc_smart0=0
venc_quality0=6
venc_not_true_3mp=0
venc_type1=0
venc_width1=704
venc_height1=576
venc_framerate1=25
venc_gop1=4
venc_rcmode1=1
venc_bitrate1=512
venc_smart1=0
venc_quality1=6
audio_enable=1
aenc_type=4
aenc_samplerate=8000
aenc_bitwidth=1
ai_volume=80
ao_volume=100
input_type=0
osd_enable=1
osd_datetime_enable=1
osd_datetime_pos=0
osd_date_fmt=0
osd_time_fmt=1
osd_show_week=0
osd_text0_enable=1
osd_text0_pos=3
osd_text0_data_utf8=HIPC
md_enable=0
md_sensitivity=10
md_threshold=90
md_rect_num=0
md_duration=20
md_output=1
pd_enable=1
pd_sensitivity=10
pd_threshold=90
pd_rect_num=0
pd_duration=20
pd_output=41
pd_show_human=1
fd_enable=1
fd_size_min=4
fd_sensitivity=50
fd_rect_num=0
fd_show_face=1
fd_live_detect=0
fd_invasion_enable=1
fd_invasion_score=20
fd_invasion_rect_num=0
fd_invasion_duration=30
fd_invasion_output=1
privacy_enable=0
privacy_rect_num=0
img_brightness=128
img_saturation=128
img_contrast=128
img_sharpness=128
img_exposure=0
img_drc_strenght=128
img_day_night_mode=1
img_day_begin=0:0:0
img_day_end=0:0:0
img_mirror=0
img_flip=0
img_wdr_enable=0
img_ircut_delay=5
img_anti_flicker_enable=0
img_anti_flicker_mode=0
img_backlight_mode=0
img_tv_standard=0
img_nr_enable=1
led_brightness=40
max_led_brightness=85
led_brightness_mode=1
img_day_night_lux=3
img_face_mode=0
img_smart_face_mode=0
img_night_fps_select=0
img_ldc_enable=0
img_rotate=0
img_day_to_night_brightness=1
img_night_to_day_brightness=1
img_whitelamp_switch=0
alarm_out_enable=0
alarm_out_delay=1
alarm_out_attach_pic=1
alarm_center_enable=0
alarm_center_port=6060
alarm_center_protocol=1
record_mode=1
record_file_length=30
record_stream=0
gb28181_enable=0
gb28181_trans_protocol=1
gb28181_trans_stream=0
gb28181_server_id=34020000002000000001
gb28181_server_domain=3402000000
gb28181_server_port=5060
gb28181_local_port=5060
gb28181_user_id=34020000001110000001
gb28181_user_name=34020000001110000001
gb28181_passwd=12345678
gb28181_register_expires=3600
gb28181_register_interval=60
gb28181_heartbeat_interval=60
gb28181_heartbeat_timeout=3
gb28181_channel_id=34020000001310000001
onvif_enable=1
onvif_port=80
onvif_auth_enable=1
rtsp_enable=1
rtsp_port=554
rtsp_auth_enable=1
qwt_enable=1
ptz_speed=63
ftp_enable=0
ftp_port=21
ftp_mode=0
http_port=80
timing_snapshot_enable=0
timing_snapshot_interval=30
timing_snapshot_output=128
snapshot_res_width=0
snapshot_res_height=0
snapshot_res_quality=0
lamp_type=2
day_night_switch_type=1
cloud_p2p_enable=0
cloud_p2p_pid=HC01
led_enable=0
sleep_mode=0
